# 第一題：
題目：給定一個矩陣m，裡面的值都大於0。
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
 
m = np.array([[0,1,10],[2,6,7]])
 
提示：使用巢狀迴圈(nested loop)加判斷式

In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

m = np.array([[0.4, 1.5, 10], [1.0, 0.254, 2.8]])
print("original matrix =")
print(m)

filtedList = list()
for x in m:
    row_list = list()
    for y in x:
        if y >= 1:
            row_list.append(1)
        else:
            row_list.append(0)
    filtedList.append(row_list)
m = np.array(filtedList)

print("after transforming:")
print(m)

original matrix =
[[  0.4     1.5    10.   ]
 [  1.      0.254   2.8  ]]
after transforming:
[[0 1 1]
 [1 0 1]]


# 第二題：
有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
 
請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
請算出班級加權平均成績，並以一個array輸出。

In [8]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

A = np.random.randint(101, size=(10,5))
B = np.random.randint(101, size=(10,5))
C = np.random.randint(101, size=(10,5))
print("A班成績 = \n{}\n".format(A))
print("B班成績 = \n{}\n".format(B))
print("C班成績 = \n{}\n".format(C))

weights=np.array([0.25,0.25,0.25,0.15,0.10])
a_dot = np.dot(A, weights)
b_dot = np.dot(B, weights)
c_dot = np.dot(C, weights)

print("A班成績加權後 = {}\n".format(a_dot))
print("B班成績加權後 = {}\n".format(b_dot))
print("C班成績加權後 = {}\n".format(c_dot))


print("A,B,C 三個班級加權平均成績各自為 {}".format(np.array([np.average(a_dot), np.average(b_dot), np.average(c_dot)])))


A班成績 = 
[[64 13  3 59 88]
 [44 13 71 29 78]
 [87 47 70 60 40]
 [77 54 23  5 46]
 [67 68 20 48 57]
 [58  5 40 68 28]
 [93 72 52  8 23]
 [68 97 96 72 24]
 [18  5 99 72 67]
 [84 20  7 58 35]]

B班成績 = 
[[19 65 80 88 55]
 [28 49 94 54 84]
 [85 99 77 92 28]
 [42 91 63 94 77]
 [12 59 31 88  9]
 [47  2 70 69 39]
 [89 80 87 27 58]
 [92 24 42 44 41]
 [39 58 44  6 19]
 [49 20 46 27  2]]

C班成績 = 
[[29 48 16 62 98]
 [97 75 26 92 97]
 [94 54 24 75 19]
 [53 18 89 33 71]
 [49 49 70 73  0]
 [34 86 96 78 54]
 [ 9 15  1 31 48]
 [81  4 30 82 43]
 [13 87 63 54 35]
 [67 17 64 30 14]]

A班成績加權後 = [ 37.65  44.15  64.    43.85  51.65  38.75  57.75  78.45  48.    39.95]

B班成績加權後 = [ 59.7   59.25  81.85  70.8   39.6   44.    73.85  50.2   38.05  33.  ]

C班成績加權後 = [ 42.35  73.    56.15  52.05  52.95  71.1   15.7   45.35  52.35  42.9 ]

A,B,C 三個班級加權平均成績各自為 [ 50.42  55.03  50.39]


# 挑戰題一：
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績
 
Hint
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return 
* 請做個測試，檢驗你的結果，方便同學評分。


In [10]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

students_grades = np.random.randint(101, size=(1, 3*30*3)).reshape(3,30,3)

print("原始成績：\n{}".format(students_grades))

def count_final(all_grades):
    weights1 = np.array([0.2, 0.35, 0.45])
    weights2 = np.array([0.4, 0.6])
    
    final_grades = list()
    
    for classNum in all_grades:
        for personGrades in classNum:
            #除去小考的成績
            no_pratices_grades = personGrades[1:]

            #以weights1計算
            after_weights1 = np.dot(personGrades, weights1)
            
            #以weights2計算
            after_weights2 = np.dot(no_pratices_grades, weights2)
            
            if after_weights1 >= after_weights2:
                final_grades.append(after_weights1)
            else:
                final_grades.append(after_weights2)
    
    return np.array(final_grades).reshape(3, 30, 1)


print("\n期末成績：\n{}".format(count_final(students_grades)))

原始成績：
[[[ 71  22  28]
  [  9  24  85]
  [ 94  27   9]
  [ 81  81  60]
  [100  89  58]
  [ 15  11  10]
  [ 37  26  55]
  [ 90  18   0]
  [ 40  56  55]
  [ 24  58  32]
  [ 93  80  25]
  [  3  18  13]
  [ 75  66  95]
  [ 54  23  89]
  [ 85  39  56]
  [ 19  72  92]
  [ 51  45  18]
  [ 82  67   3]
  [ 64  41  21]
  [ 13  16   4]
  [ 45  40  41]
  [ 84  37   7]
  [ 27  49  66]
  [ 72  55  22]
  [ 77  86  82]
  [ 27  76  73]
  [ 89   8  50]
  [ 32  54  28]
  [ 40  15  28]
  [ 38  96  64]]

 [[ 81  72  19]
  [ 10  36  91]
  [ 67  38  88]
  [ 65  97  21]
  [ 64  37  19]
  [ 80  11  84]
  [ 79  15   5]
  [ 71   2  10]
  [  5  84  64]
  [ 34  10  58]
  [  9  63  71]
  [ 51  43  45]
  [ 96  84  64]
  [ 47  84  96]
  [ 10  41  25]
  [ 75  80  30]
  [ 54  56  29]
  [ 78  22  78]
  [ 43  53   4]
  [ 74  13  42]
  [ 91  41  19]
  [ 17  15   1]
  [ 83  33   3]
  [ 42  63  14]
  [ 23  78  23]
  [ 71  37   1]
  [  0  42  34]
  [ 66  65  30]
  [  6  53  43]
  [ 73  50  42]]

 [[ 32   7  47]
  [  9  38  22

# 世紀魔鬼挑戰題（做完可以直接得到一百分）：
美食沙漠的餐點推薦系統
Susan是個數學高手，每天專心研究高深數學理論，因此沒有時間想每一餐要吃什麽，
請依照他的需求幫他做出各餐的推薦餐點。
 
給定以下list:
breakfast_list = ['古早味', '德合香', '布朗奇早餐', '星巴克', '小貓咪', '傳香飯糰', '米塔', '麥當勞', '摩斯', '7-11', '全家']
lunch_and_dinner_list = ['小公寓', '波波恰恰', '湯饌', '享窩咖啡', '湯包', '殺人魔王', '呷麵騎士', '提洛斯', '蝴蝶漾', '東京小城', '金鰭', '樂山', 'My麵屋', '李氏餐酒館', '里克', '水煎包', '憩賢樓', '高句麗', '魯智深', '敏忠', '大正亭', '阿里郎', '鬼匠', 'Juicy Bun', '滇味廚房']
high_price_list = ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房']
snack_list = ['豆花', '政大烤場', '丐幫滷味', '鹹水雞']
 
請遵守以下規則：
1.依照早餐-午餐-晚餐的順序決定
2.餐點必須用亂數決定
3.除了定義以上的list，不可以在其他地方出現字串
(也就是說不可以決定午餐吃'小公寓'後，另外定義dinner = ['波波恰恰', '湯饌', '享窩咖啡',...]）
4.一天裡面只可以有一餐是屬於high_price
5.午餐跟晚餐我不想吃同一家
6.如果當天三餐都沒有屬於high_price的話，就要吃宵夜
 
範例輸出

Case 1:
早餐：古早味
午餐：提洛斯
晚餐：大正亭
宵夜：鹹水雞

Case 2:
早餐：傳香飯糰
午餐：小公寓
晚餐：鬼匠

In [71]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

breakfast_list = ['古早味', '德合香', '布朗奇早餐', '星巴克', '小貓咪', '傳香飯糰', '米塔', '麥當勞', '摩斯', '7-11', '全家']
lunch_and_dinner_list = ['小公寓', '波波恰恰', '湯饌', '享窩咖啡', '湯包', '殺人魔王', '呷麵騎士', '提洛斯', '蝴蝶漾', '東京小城', '金鰭', '樂山', 'My麵屋', '李氏餐酒館', '里克', '水煎包', '憩賢樓', '高句麗', '魯智深', '敏忠', '大正亭', '阿里郎', '鬼匠', 'Juicy Bun', '滇味廚房']
snack_list = ['豆花', '政大烤場', '丐幫滷味', '鹹水雞']
high_price_list = ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房']

dailyOrder = np.eye(4)[np.random.randint(4)]
print(dailyOrder)

#早餐
rand_b = np.random.randint(len(breakfast_list))
if dailyOrder[0] == 0 and breakfast_list[rand_b] in high_price_list:
    while(breakfast_list[rand_b] in high_price_list):
        rand_b = np.random.randint(len(breakfast_list))
elif dailyOrder[0] == 1 and breakfast_list[rand_b] not in high_price_list:
    while(breakfast_list[rand_b] not in high_price_list):
        rand_b = np.random.randint(len(breakfast_list))
# print(breakfast_list[rand_b])

#午餐
rand_l = np.random.randint(len(lunch_and_dinner_list))
if dailyOrder[1] == 0 and lunch_and_dinner_list[rand_l] in high_price_list:
    while(lunch_and_dinner_list[rand_l] in high_price_list):
        rand_l = np.random.randint(len(lunch_and_dinner_list))
elif dailyOrder[1] == 1 and lunch_and_dinner_list[rand_l] not in high_price_list:
    while(lunch_and_dinner_list[rand_l] not in high_price_list):
        rand_l = np.random.randint(len(lunch_and_dinner_list))
        
# print(lunch_and_dinner_list[rand_l])

#晚餐
rand_d = np.random.randint(len(lunch_and_dinner_list))
if rand_d == rand_l or (dailyOrder[2] == 0 and lunch_and_dinner_list[rand_d] in high_price_list):
    while(lunch_and_dinner_list[rand_d] in high_price_list or rand_d == rand_l):
        rand_d = np.random.randint(len(lunch_and_dinner_list))
elif rand_d != rand_l and (dailyOrder[2] == 1 and lunch_and_dinner_list[rand_d] not in high_price_list):
    while(lunch_and_dinner_list[rand_d] not in high_price_list or rand_d == rand_l):
        rand_d = np.random.randint(len(lunch_and_dinner_list))
# print(lunch_and_dinner_list[rand_d])

#宵夜
if dailyOrder[3] == 0:
    #沒有宵夜
    print("早餐：{}\n午餐：{}\n晚餐：{}".format(breakfast_list[rand_b], lunch_and_dinner_list[rand_l], lunch_and_dinner_list[rand_d]))
else:
    #有宵夜
    print("早餐：{}\n午餐：{}\n晚餐：{}\n宵夜：{}".format(breakfast_list[rand_b], lunch_and_dinner_list[rand_l], lunch_and_dinner_list[rand_d], snack_list[np.random.randint(len(snack_list))] ))
    
#high_price_list = ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房']

[ 0.  0.  1.  0.]
早餐：德合香
午餐：湯饌
晚餐：李氏餐酒館
