# 第一題_算閏年：
<br>請定義一個函式，讀進一個年份，輸出是不是閏年。
<br>提示：
<br>目前使用的格里高利曆閏年規則如下：
<br>
<br>4的倍數是可能的。
<br>100的倍數是不可能的。
<br>400的倍數是可能的。

In [67]:
def leap_year(year):
    int_year = int(year)
    
    if int_year % 4 != 0:
        return "平年"
    else:
        if int_year % 100 != 0:
            return "閏年"
        else:
            if int_year % 400 != 0:
                return "平年"
            else:
                return "潤年"

#測試
print("2016 = " + leap_year(2016))
print("2017 = " + leap_year(2017))
print("2018 = " + leap_year(2018))
print("2019 = " + leap_year(2019))


2016 = 閏年
2017 = 平年
2018 = 平年
2019 = 平年


# 第二題_請實作五乘五矩陣的矩陣加法函式：
<br>ex:
<br>def matrix_plus(m1+m2):

In [60]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def matrix_plus(m1, m2):
    m1 = np.matrix(m1)
    m2 = np.matrix(m2)
    return m1+m2


#測試
a = np.array([np.arange(0,25)])
a = np.resize(a, (5,5))
b = np.array([np.arange(100,125)])
b = np.resize(b, (5,5))

print(matrix_plus(a, b))




[[100 102 104 106 108]
 [110 112 114 116 118]
 [120 122 124 126 128]
 [130 132 134 136 138]
 [140 142 144 146 148]]


# 第三題_錄取分數表格
<br>小明今年考大學
<br>依照 [“國文”, “英文”, “數甲”, “數乙”, “物理”, “化學”, “生物”, “歷史”, “地理”, “公民”]
<br>他的分數分別是 [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
<br>而他所想申請的大學各系採計的科目權重分別是
<br>{
<br>“土語系”: [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
<br>“財政系”: [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
<br>“金融系”: [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
<br>“國貿系”: [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
<br>“會計系”: [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
<br>“法律系”: [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
<br>“公行系”: [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
<br>“應數系”: [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
<br>“教育系”: [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
<br>}
<br>
<br>請幫他做出一個表格
<br>第一欄顯示科系
<br>接下來顯示權重 並標示科目
<br>最後一欄顯示加權分數

## Hint
<br>在dataframe最左邊那欄叫index 最上面叫columns
<br>小明的分數跟各科系權重可以直接複製上面的文字使用
<br>表格裡面的內容可以用for迴圈跑過個科系 取出該科系的權重 然後整理成一個二維的list
<br>加權分數的算法可以試試看直接把表格跟分數相乘 會有意想不到的結果喔
<br>如何算加權分數可以參考影片5.4: 「用熊貓做基本數據分析」

In [62]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

subject_weight = { 
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0], 
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0], 
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0], 
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0], 
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0], 
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1], 
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25], 
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0], 
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0] 
} 

dep_names = subject_weight.keys()
sub_names = ["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"] 
grades = np.array([86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6])

weight_matrix = []
for key, value in subject_weight.items():
    weight_matrix.append(value)
    
weight_matrix = np.array(weight_matrix)
subweight_df = pd.DataFrame(data= weight_matrix, columns = sub_names, index=list(dep_names))
subweight_df["加權分數"] = (grades*subweight_df[sub_names]).sum(1)

subweight_df


國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民     加權分數
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  398.600
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00  642.450
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  481.550
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00  461.300
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00  508.900
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25  436.975
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00  350.350
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00  570.075
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00  589.200

# 挑戰題一_Bubble Sort
<br>Geoffrey是個喜歡自動化的老師，某次期中考過後，他想要把學生的成績用電腦自動排序，於是他請Andrew幫忙開發這個高難度的程式…
<br>
<br>限制：不可以使用Python內建的sort()
<br>
<br>提示：
<br>
<br>每回合都把該回合範圍內最小的數搬到最左邊，最後就可以排好所有的數
<br>搬運的方式可以透過兩兩互換

In [70]:
def bubble_sorting(grades_list):
    for i in range(0, len(grades_list)-1):
        for j in range(0, len(grades_list)-1-i): 
            if grades_list[j] > grades_list[j+1]:
                tmp = grades_list[j]
                grades_list[j] = grades_list[j+1]
                grades_list[j+1] = tmp
    
    return grades_list

#測試
stu_grades = [20, 50, 15, 10, 2, 65, 85, 33, 46, 98, 66, 28, 29]
print(bubble_sorting(stu_grades))

[2, 10, 15, 20, 28, 29, 33, 46, 50, 65, 66, 85, 98]
